import type { Metadata } from "next";
import "./globals.css";
import { chillax, synonym, zcool_XiaoWei, ma_Shan_Zheng, notoSans_SC } from "../fonts";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <SessionProvider session={session}>
        <body
          className={`${zcool_XiaoWei.variable} ${ma_Shan_Zheng.variable} ${notoSans_SC.variable} ${chillax.variable} ${synonym.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
          <Toaster position="bottom-right" />
        </body>
      </SessionProvider>
    </html>
  );
}
