import type { Metadata } from "next";
import "./globals.css";
import { chillax, synonym, zcool_XiaoWei, ma_Shan_Zheng, notoSans_SC } from "../fonts";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${zcool_XiaoWei.variable} ${ma_Shan_Zheng.variable} ${notoSans_SC.variable} ${chillax.variable} ${synonym.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
